site_name: PVE Cloud Documentation

nav:
  - index.md
  - bootstrap.md
  - kubernetes.md
  - terraform.md
  - tdd.md
  - faq.md
  - contributing.md
  - Schemas:
    - schemas

theme:
  name: material
  features:
    - toc.follow
    - toc.integrate 

plugins:
  - search
  - include_dir_to_nav
