site_name: PVE Cloud Documentation

nav:
  - index.md
  - bootstrap.md
  - kubernetes.md
  - terraform.md
  - tdd.md
  - faq.md
  - contributing.md
  - Schemas:
    - schemas

theme:
  name: material
  palette:
    scheme: default

  features:
    - toc.follow
    - toc.integrate
    - search.suggest

plugins:
  - search
  - include_dir_to_nav
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      theme:
        dark: material/indigo-dark