---
# tasks file for set_dns01_ionos
- debug:
    msg: "{{ ret_acme_challenge['challenge_data_dns'] | dict2items }}"


- name: try to select existing data
  alchemy_read:
    pg_conn_str: "{{ pg_conn_str }}"
    table: px_cloud_secrets
    where:
      cloud_domain: "{{ pve_cloud_domain }}"
      secret_name: "ionos-api-key"
  register: ionos_secret_query

- set_fact:
    ionos_api_key: "{{ ionos_secret_query.query_result[0]['secret_data'] }}"

- debug:
    var: ionos_api_key

- ionos_dns:
    ionos_api_key: "{{ ionos_api_key }}"
    challenge_data_dns: "{{ ret_acme_challenge['challenge_data_dns'] | dict2items }}"
