- name: Slurp secrets 
  hosts: target_pve
  roles:
    - slurp_cluster_secrets
    
# Acme certificates
- name: Acme 
  hosts: localhost
  roles:
    - pxc.cloud.parse_cluster_secrets
  tasks:
    - include_role:
        name: pxc.cloud.apply_acme_certs
      when: acme_method is defined and cluster_cert_entries | length > 0