---
# defaults file for haproxy_conf
k8s_workers: {'query_result': []}
k8s_masters: {'query_result': []}
k8s_ingress_rules: {'query_result': []}
k8s_tcp_proxies: {'query_result': []}
k8s_ext_control_planes: {'query_result': []}

auto_http_redirect: true